<?php
// $Id$
/**
 * @file
 * Provide custom breadcrumbs for views pages.
 */
module_load_include('inc', 'custom_breadcrumbs', 'custom_breadrumbs.admin');

/**
 * Implementation of hook_cb_breadcrumb_info().
 *   @return an array with elements 
 *     'table' indicating the db_table to load the breadcrumb from,
 *     'field' a unique field of the database table used to identify the breadcrumb
 *     'type' a string used for indicating the breadcrumb type on the admin list
 */
function custom_breadcrumbs_views_cb_breadcrumb_info() {
  $breadcrumb_type_info = array();
  $breadcrumb_type_info[] = array('table' => 'custom_breadcrumbs_views', 'field' => 'views_path', 'type' => 'views');
  return $breadcrumb_type_info;
}

/**
 * Implementation of hook_menu().
 */
function custom_breadcrumbs_views_menu() {
  $items = array();

  $items['admin/build/custom_breadcrumbs/views/add'] = array(
    'title'            => 'Views Pages',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('custom_breadcrumbs_views_form', 'views'),
    'access callback'  => 'user_access',
    'access arguments' => array('administer custom breadcrumbs'),
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 5,
  );

  $items['admin/build/custom_breadcrumbs/views/edit'] = array(
    'title'            => 'Edit custom breadcrumb for views',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('custom_breadcrumbs_views_form', 'views'),
    'access callback'  => 'user_access',
    'access arguments' => array('administer custom breadcrumbs'),
    'type'             => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_views_pre_render().
 */
function custom_breadcrumbs_views_views_pre_render(&$view) {
  // Don't really do anything with the view. This is just a pretense to insert a breadcrumb.
  global $language;
  $languages = array('language' => $language->language, 'all' => '');

  foreach ($view->display as $display) {
    // Identify allowed displays for breadcrumb replacement.
    if (!_allowed_display($display)) continue;
    $name = $display->display_options['path'];
    $breadcrumbs = custom_breadcrumbs_load_breadcrumbs('custom_breadcrumbs_views', NULL, array('views_path' => $name), $languages);
    if (!empty($breadcrumbs)) {
      if ($breadcrumb = custom_breadcrumbs_select_breadcrumb($breadcrumbs, $view)) {
        custom_breadcrumbs_set_breadcrumb($breadcrumb, $view);
        return;
      }
    }
  }
  if (variable_get('custom_breadcrumbs_set_menu_breadcrumb', FALSE)) {
    // If a views breadcrumb has not been defined for this view, then use default menu structure.
    custom_breadcrumbs_set_menu_breadcrumb();
  }
}

/**
 * Displays an edit form for a views breadcrumb.
 */
function custom_breadcrumbs_views_form(&$form_state, $type) {
  $form = array();
  $breadcrumb = NULL;
  $bid = arg(5);
  if (isset($bid)) {
    drupal_set_title('Edit Custom Breadcrumb for View');
    $breadcrumb = array_pop(custom_breadcrumbs_load_breadcrumbs('custom_breadcrumbs_views', NULL, array('bid' => $bid)));
  }
  else {
    drupal_set_title('Add Custom Breadcrumb for View');
  }
  $options = array();
  $views =  views_get_all_views();
  foreach ($views as $view) {
    if (!$view->disabled) {
      foreach ($view->display as $display) {
        if (_allowed_display($display)) {
          $name = $display->display_options['path'];
          $options[$name] = $name;
        }
      }
    }
  }
  $form['views_path'] = array(
    '#type' => 'select',
    '#title' => t('Views Path'),
    '#required' => TRUE,
    '#options' => $options,
    '#description' => t('The path to the view that this custom breadcrumb trail will apply to.'),
    '#default_value' => $bid ? $breadcrumb->views_path : NULL,
    '#weight' => -10,
  );
  // Store information needed to save this breadcrumb.
  $form['#table'] = 'custom_breadcrumbs_views';
  $form += custom_breadcrumbs_common_form_elements($bid, $breadcrumb);
  $form['visibility_php']['#description'] = t('Determine whether this breadcrumb should be displayed by using a snippet of PHP to return TRUE or FALSE.');
  $form['#submit'][] = 'custom_breadcrumbs_form_submit';
  $form['#validate'][] = 'custom_breadcrumbs_form_validate';

  return $form;
}

/**
 *  Helper function to specify allowed views displays for breadcrumb placement.
 */
function _allowed_display($display) {
  if (drupal_substr($display->id, 0, 5)  == 'page_' || drupal_substr($display->id, 0, 9)  == 'calendar_') {
    if (isset($display->display_options['path']) && !$display->handler->view->is_attachment) {
      return TRUE;
    }
  }
  return FALSE;
}
